version: '3.8'

services:
  postgres:
    image: postgres
    container_name: java-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgresql

  app:
    build: ./
    container_name: java-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgresql
    ports:
     - "9090:9090"
    depends_on:
      - postgresql