version: '3.8'

services:
  postgresdb:
    image: postgres
    container_name: java-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres

  app:
    image: service
    build:
      context: .
      dockerfile: service.Dockerfile
    container_name: java-app
    ports:
      - "9090:9090"
    depends_on:
      - postgresdb
    command: bash -c "java -jar /home/GoCloudCamp/target/GoCloudCamp-0.0.1-SNAPSHOT.jar"